name: Cancel

on:
  pull_request:
    branches: [master]

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflows-action@0.9.0
        with:
          workflow_id: ci.yml
          access_token: ${{ github.token }}